config/routes.rb
Rails3JqueryUjsExample::Application.routes.draw do

  root :to => "main#index"

  match "up" => "main#up", :as => :up 
  match "down" => "main#down", :as => :down
  match "left" => "main#left", :as => :left
  match "right" => "main#right", :as => :right

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  end

  def up 
  end 

  def down 
  end

  def left 
  end

  def right 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.haml
!!! 
%html
  %head
    %meta{'http-equiv' => 'Content-Type', :content => 'text/html;charset=UTF-8'}/
    %title
      Rails3JqueryUjsExample 
    %meta{'name' => 'author', :content => 'takuyan'}/
    != stylesheet_link_tag "application"
    %script{:type => "text/javascript", :src => "http://www.google.com/jsapi"}
    %script{:type => "text/javascript"}
      google.load("jquery", "1.4.4");
      google.load("jqueryui", "1.8.7");
    != javascript_include_tag :defaults
    != csrf_meta_tag
  %body
    #wrapper
      #header 
        != link_to image_tag("up_arrow.png"), up_path, :remote => true, :method => :post, :id => "up", :class => "move"
        != link_to image_tag("down_arrow.png"), down_path, :remote => true, :method => :post, :id => "down", :class => "move"
        != link_to image_tag("left_arrow.png"), left_path, :remote => true, :method => :post, :id => "left", :class => "move"
        != link_to image_tag("right_arrow.png"), right_path, :remote => true, :method => :post, :id => "right", :class => "move"

      #container 
        != yield :layout
    #overlay 

app/views/main/down.js.erb
var position = $("#logo").position();
$("#logo").css({
  top: parseInt(position.top) + 50
});

app/views/main/index.html.haml
!= image_tag "rails.png", :id => "logo"

app/views/main/left.js.erb
var position = $("#logo").position();
$("#logo").css({
  left: position.left - 50
});

app/views/main/right.js.erb
var position = $("#logo").position();
$("#logo").css({
  left: position.left + 50
});

app/views/main/up.js.erb
var position = $("#logo").position();
$("#logo").css({
  top: parseInt(position.top) - 50
});